version: '3'
services:
  test:
    build: 
      context: .
      dockerfile: Dockerfile.test
  web:
    depends_on:
      - test
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes: 
      - /app/node_modules
      - .:/app